### ISSUE TITLE
AndroidStudio use xmake bug

### ISSUE THREAD

**Issue by jackyglony** [tboox/xmake-idea#1]
AndroidStudio 在使用xmake 插件时，导致普通的java程序无法运行，报：
Android Studio XMake threw an uncaught ProcessNotCreatedException 错误？

**Comment by waruqi** [comment]
能详细描述下 复现场景么？我这边好分析下。

**Comment by waruqi** [comment]
我已经修复这个问题，请更新到1.0.5版本再试下
